### ISSUE TITLE
When I tested a disposable email on V2, it comes back as invalid. 

### ISSUE THREAD

**Issue by zerobounce** [afrase/zerobounce#9]
Use "test@hushmail.com" - should be status = "do_not_mail" with the sub-status of "role_based", but returns "invalid" as a status.

**Comment by afrase** [comment]
I'm getting a status of `do_not_email` and a sub-status of `disposable`. This client basically just returns the results that the Zerobounce API returns so if you are getting an incorrect status you might want to contact there support.

**Comment by afrase** [comment]
Wow didn't even notice who created the issue.
It looks like you guys fixed it on your end though.

**Comment by dawngreen** [comment]
So, is this issue fixed?

**Comment by zerobounce** [comment]
We might be using your library wrong, but I got the same status as DawnGreen when I tested.

**Comment by afrase** [comment]
If you add the environment variable `ZEROBOUNCE_API_DEBUG` the client will output the requests.
Here is what I get.

```
pry(main)> Zerobounce.validate(email: 'test@hushmail.com').status
I, [2019-05-24T14:25:04.499964 #14115]  INFO -- : get https://api.zerobounce.net/v2/validate?api_key=[REMOVED]&email=test%40hushmail.com&ip_address=
D, [2019-05-24T14:25:04.500041 #14115] DEBUG -- request: User-Agent: "ZerobounceRubyGem/0.1.0"
I, [2019-05-24T14:25:07.779482 #14115]  INFO -- Status: 200
D, [2019-05-24T14:25:07.779578 #14115] DEBUG -- response: date: "Fri, 24 May 2019 18:25:53 GMT"
content-type: "application/json; charset=utf-8"
transfer-encoding: "chunked"
connection: "close"
set-cookie: "__cfduid=de694f637f7970172d88f2ff1302bec051558722353; expires=Sat, 23-May-20 18:25:53 GMT; path=/; domain=.zerobounce.net; HttpOnly; Secure"
cache-control: "public, max-age=691200"
x-powered-by: "ASP.NET"
access-control-allow-origin: "*"
access-control-allow-methods: "GET"
access-control-allow-headers: "Content-Type"
cf-cache-status: "HIT"
expires: "Sat, 01 Jun 2019 18:25:53 GMT"
strict-transport-security: "max-age=31536000; includeSubDomains; preload"
x-content-type-options: "nosniff"
expect-ct: "max-age=604800, report-uri=\"https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct\""
vary: "Accept-Encoding"
server: "cloudflare"
cf-ray: "4dc150927ca72602-ORD"
=> :do_not_mail
```

**Comment by dawngreen** [comment]
Here are my results: 

`Finished call of Zerobounce for order 25628083, venue 1343, email test@hushmail.com, valid false : 2019-05-30 09:31:14 -0500`

**Comment by dawngreen** [comment]
Following back up on this. You can see my call, `Zerobounce.valid?(email)`, returns `false`.  Shouldn't the `do_not_mail` status return a valid status since you're saying it is "disposable".

**Comment by afrase** [comment]
If you want `Zerobounce.valid?(email)` to return `true` for `do_not_mail` statuses you can do `Zerobounce.config.valid_statuses << :do_not_mail`.
